### ISSUE TITLE
Daemon mode not working on Raspberry Pi

### ISSUE THREAD

**Issue by t1m0thyj** [xlab/matchbox-keyboard#13]
I'm passing the command line argument `--daemon` and the keyboard isn't showing up. The README says:

> The IM must be added to your gtk setup (See /etc/gtk-2.0/gtk.immodules, gtk-query-immodules-2.0 )

The problem is that I'm not sure how to do this. If more details could be provided, I would greatly appreciate it.

**Comment by xlab** [comment]
> I'm passing the command line argument --daemon and the keyboard isn't showing up.

The keyboard in daemon runs as a background process, listening to events. To send it a trigger event, use applet (https://github.com/xlab/matchbox-keyboard/tree/matchbox-keyboard-xlab/applet) or a program called matchbox-keyboard-toggler see https://github.com/xlab/matchbox-keyboard/issues/7#issuecomment-269673304 I always been using that toggler.

**Comment by t1m0thyj** [comment]
Thanks for the reply. I only needed the keyboard in an app I was developing using Qt, so rather than running it in daemon mode, I figured out how to use QX11EmbedContainer to embed it using the `--xid` argument. That gives me more direct control over it and works fine for my purposes.
