### ISSUE TITLE
Support libpng16

### ISSUE THREAD

**Issue by normanr** [xlab/matchbox-keyboard#2]
matchbox-keyboard is being used by [kterm](https://github.com/bfabiszewski/kterm) (kindle terminal emulator) and a recent kindle update removed libpng12 in favour of libpng16.

It looks like the changes to support libpng15 are quite small: https://github.com/mmoselhy/poky-e100-danny/commit/db07a94e0fe400390e3bbe49a5be10aff1ea3619, so they may be all that's needed for libpng16 too.

**Comment by normanr** [comment]
It looks like [mwilliams03/matchbox-keyboard](https://github.com/mwilliams03/matchbox-keyboard) also has the 1.5 patches merged

**Comment by xlab** [comment]
From `libpng-1.2.6/example.c`:

> The png_jmpbuf() macro, used in error handling, became available in libpng version 1.0.6.

It seems that adding the patch required for 1.5 will be compatible with libpng12 distros too, also their patch to `configure.ac` looks good in general. I'll add that.

**Comment by xlab** [comment]
I'm too lazy to import those Ross' commits. You may check if it works now.
