### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by jaKenobi** [xlab/matchbox-keyboard#23]
Hi,
Could it be possible to add the option to make the keyboard always on top of screen ? To make sure that even a fullscreen app that runs will be overwritten by the keyboard?

Thanks

**Comment by xlab** [comment]
` -v,--override            Absolute positioning on the screen` - isn't this helping?

**Comment by xlab** [comment]
Also 

```
   -g,--geometry <HxW.y.x>  Specify keyboard's geometry 
  (ex: -g 200x800; -g 0x800.200.0; -g 0x0.0.50; zeroes mean "by-default")
```

to match the screen dimensions

**Comment by jaKenobi** [comment]
Yes that does the trick thank you!
I knew about the -g, but I thought that the -v was about position on the screen as like in the center or at 0,0 something like that.
Should've tried it haha.
