### ISSUE TITLE
make the keyboard always on top

### ISSUE THREAD

**Issue by ghost** [xlab/matchbox-keyboard#4]
I guess the keyboard was made to work with tiling WMs like awesome and stuff. But I don't use those I use GNOME and unity.
other virtual keyboards are able to stay on top of all windows, and that just makes sense. and since the others can do it, then I'm sure it's doable.

I tried to hack on it myself. I don't know much xlib or GUI in general to be honest. I followed [this answer](http://stackoverflow.com/questions/4345224/x11-xlib-window-always-on-top) but the `_NET_WM_STATE_ABOVE` thing didn't work (at least on unity).

I asked a question [here](http://unix.stackexchange.com/questions/256224/make-x11-window-always-on-top-virtual-keyboard/256262#256262) but got nothing new yet.

so I was wondering since you're more experienced if you could give me a hint on what should be done?

**Comment by xlab** [comment]
Hi!
Have you tried to use `-v,--override            Absolute positioning on the screen` option?
Anyway, I hacked into this lib ~7 years ago, can't remember anything :(

**Comment by ghost** [comment]
Well that was helpful :-D thanks. I think I might need to rewrite the UI to gtk or something. I don't think that will be easy though.

Sent from my Sony Xperia™ smartphone

---- Maxim Kupriianov wrote ----

Hi!
Have you tried to use `-v,--override            Absolute positioning on the screen` option?
Anyway, I hacked into this lib ~7 years ago, can't remember anything :(

---

**Comment by xlab** [comment]
Try to write something new from scratch, that'll be easier :)
This is an old piece of junk.

**Comment by ghost** [comment]
That's an old piece of junk that has good naming convention and reads keyboard layouts from xml files which happens to be exactly what I want :D
That makes it a very good old piece of junk :D
