### ISSUE TITLE
Can't find a way to activate "shrink neighbour windows"

### ISSUE THREAD

**Issue by ernstp** [xlab/matchbox-keyboard#6]
When and how is this feature activated?
Limitations?

**Comment by xlab** [comment]
This highly depends on the WM you're using, achieved by sending special hints and setting the size properties, see https://github.com/xlab/matchbox-keyboard/blob/matchbox-keyboard-xlab/src/matchbox-keyboard-ui.c#L944 and other places.

In 2009 I primarily used openbox (as in LXDE, etc) so I made this KB working fine with it, also works for matchbox (Nokia N810, etc) and some others that I tested along. If you have something up to date you should modify the code so the corresponding hints and WM options would get used.

That's a piece of crap in C someone wrote in 2005 and some kid (me) hacked back in 2009.
Totally not worth investing any time to do additional development ;)
