### ISSUE TITLE
no icon in taskbar raspberry pi

### ISSUE THREAD

**Issue by si458** [xlab/matchbox-keyboard#7]
Hi,
managed to get it installed on my raspberry pi without any issue
only issue i have is when i click the MIN button on bottom right, it vanishes and i cant get it back?
the also doesnt appear to be an icon in the taskbar?
when i look using task manager, i can see its still running in the background tho?
im using the latest raspbian edition out with the new PIXEL desktop

**Comment by xlab** [comment]
Hi, have you tried this applet?
https://github.com/xlab/matchbox-keyboard/tree/matchbox-keyboard-xlab/applet
not sure if it works, I used this keyboard back in 2009 and it was already legacy :)

By the way, back in 2009 I've been using this program:
https://gist.github.com/xlab/3104348

I just compiled it and created a shortcut in my panel to simply invoke it!
It's a simple executable that does 1 thing — toggles the keyboard.
Note, you should run the kbd with `-d` flag:

```
-d,--daemon              Run in 'daemon' mode (for remote control)
```

Good luck and happy New Year. Have fun!
